version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    env_file:
      - ../.env
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - ../output:/app/output
      - ../src:/app/src
      - ../tests:/app/tests
      - ../pytest.ini:/app/pytest.ini
    env_file:
      - ../.env
    command: pytest -v

  # Redis for caching (optional but recommended)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
