AWSTemplateFormatVersion: '2010-09-09'
Description: 'Redis stack for vMini-engine'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where Redis will be deployed

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for Redis cluster

Resources:
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref 'AWS::NoValue'  # Will be updated by update-redis-sg.sh
      Tags:
        - Key: Name
          Value: vMini-engine-redis-sg

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis cluster
      SubnetIds: !Ref SubnetIds

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheNodes: 1
      VpcSecurityGroupIds: 
        - !Ref RedisSecurityGroup
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      Port: 6379
      Tags:
        - Key: Name
          Value: vMini-engine-redis

Outputs:
  RedisEndpoint:
    Description: Redis endpoint address
    Value: !GetAtt RedisCluster.RedisEndpoint.Address

  RedisPort:
    Description: Redis port
    Value: !GetAtt RedisCluster.RedisEndpoint.Port

  RedisSecurityGroupId:
    Description: Security group ID for Redis
    Value: !Ref RedisSecurityGroup 