AWSTemplateFormatVersion: '2010-09-09'
Description: 'Storage Configuration for vMini-engine'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, production]

Resources:
  StoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub vmini-engine-stories-${Environment}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  StoryBucketName:
    Description: Name of the S3 bucket for stories
    Value: !Ref StoryBucket
    Export:
      Name: !Sub ${AWS::StackName}-StoryBucketName 