name: Deploy Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Vercel
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'frontend/')
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }} 